name: CI

on:
  workflow_call

concurrency:
  group: ci-tests-${{ github.ref }}-1 # can be referenced in other workflow files
  cancel-in-progress: true

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: echo 'Hello world'



