name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-tests:
    strategy:
      matrix: 
        command: [lint, "test:ci", e2e] #needs quotes cause color in name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: ${{ matrix.command }}
        run: yarn ${{ matrix.command }}



